### ISSUE TITLE
VR polarity minor mess

### ISSUE THREAD

**Issue by rusefillc** [mck1117/proteus#57]
![image](https://user-images.githubusercontent.com/48498823/88334844-5b14b800-cd00-11ea-9f28-5589b6e5f4ba.png)

**Comment by mck1117** [comment]
While this wasn't intentional, with the polarity flipped, the behavior actually matches that of microRusefi.  The TLE8888 is a non-inverting setup, while the MAX992x is inverting, so flipping the pins makes them both behave the same way.

See both datasheets (TLE on top, MAX on bottom):
<img width="876" alt="image" src="https://user-images.githubusercontent.com/568254/88603892-012b2f80-d02b-11ea-800b-9e10521f9f07.png">

Besides, it's easy to switch the polarity in software.

So while technically wrong, I'm going to leave it wrong.

**Comment by mck1117** [comment]
Comment added on the schematic explaining the logic above, with a link to this issue.

**Comment by rusefillc** [comment]
Maybe a comment on the schematics confirming that this is now a feature?
