### ISSUE TITLE
Proteus ETB1 MR capacitor damage

### ISSUE THREAD

**Issue by ErichPopp** [mck1117/proteus#58]
With no grounds connected to the black 23pin connector and while powered on, the black 35 pin connector was disconnected and reconnected. When it was connected again the capacitor failed and the trace between the MR pin and capacitor was vaporized.

**Comment by ErichPopp** [comment]
![446F2503-7C0A-4BC6-91B3-928C2C3AFE21](https://user-images.githubusercontent.com/68789750/88464495-4283d980-ce89-11ea-8461-fffc2850db4b.jpeg)
![Uploading 5DC4CC11-C684-4CB4-BEEA-9F0394F303B0.jpeg…]()

**Comment by mck1117** [comment]
Does the cap measure as a short circuit?

**Comment by ErichPopp** [comment]
I ended up not getting back out there yesterday. It’s my birthday weekend
so I may not be out there again until Monday. I’ll let you know as soon as
I can.

**Comment by mck1117** [comment]
No problem!

**Comment by rusefillc** [comment]
Happy Birthday @ErichPopp!

**Comment by mck1117** [comment]
@ErichPopp have a chance to test that cap?

**Comment by mck1117** [comment]
I seem to remember the cap ended being a short circuit, probably due to a crack in it from the proximity to the connector.  In case it was a crack due to overvoltage (inductive spike), an electrolytic was added to the `12v_MR` net in 0.4 as extra insurance, in addition to the ceramic near each ETB driver.
