### ISSUE TITLE
JLC fab electrolytic capacitors?

### ISSUE THREAD

**Issue by rusefillc** [mck1117/proteus#73]
microRusEFI has electrolytic capacitor populated by JLC is that possible for Proteus?

**Comment by rusefillc** [comment]
is it about Anti-Vibe vs non-Anti-Vibe?

**Comment by mck1117** [comment]
It's about anti vibe, and that chiniesium electrolytics have been notoriously bad in the past.  I trust Panasonic/Nichicon/etc far more than I do Lelon.

I'm actually considering instead switching to thru hole electrolytics because they're easier to solder and even sturdier than even the anti vibe SMD units.

**Comment by mck1117** [comment]
potential option like PLV1H680MDL1

**Comment by mck1117** [comment]
electrolytics are now thru hole, EEH-AZF1H560B and can go on either side of the board
